insert into Goods values (1,'辛拉面Ramen',1.42,'El producto "NONGSHIM Noodles Coreanos Picantes Clásicos" 120g.','1.jpg');
insert into Goods values (2,'Galletas de la fortuna Wong Wong',1.71,'es una galleta taiwanesa de 56g ','2.jpg');
insert into Goods values (3,'ciruela salada',1.41,'El ciruelo verde tiene un sabor dulce y plano, con frutas grandes, cáscara delgada, carne gruesa, núcleo pequeño, textura crujiente, jugosa y ácida. Es rico en varios aminoácidos y vitamina C. Es conocido como "el rey de las frutas frescas" y "alimento saludable naturalmente verde", y es muy popular en el mercado japonés.','3.jpg');
insert into Goods values (4,'caramelo de leche',3.04,'Caramelos de leche sabor té verde (matcha) de 150g ','4.jpg');
insert into Goods values (5,'rosquilla de sémola',4.05,'Galletas de sémola sabor huevo suave de XuFuJi, 311g','5.jpg');
insert into Goods values (6,'Rollo de huevo crujiente',3.04,'Rollos de huevo crujientes con sabor a sésamo rico de Kangshifu, 108g','6.jpg');
insert into Goods values (7,'Gelatina de azúcar moreno',1.82,'Gelatina de azúcar moreno de Xiaolongkan, 210g','7.jpg');
insert into Goods values (8,'Tofu seco marinado',1.32,'Tofu seco marinado sabor picante de Jiānzǐ, 72g','8.jpg');
insert into Goods values (9,'Peces pequeños de la marca Jinzai',3.25,'Sabor picante en bolsa de 110 gramos','9.jpg');
insert into Goods values (10,'patatas fritas con sabor a pepino',2.64,'Papas fritas sabor a pepino de Lay''s, 70g','10.jpg');
insert into Goods values (11,'sopa de mango y lichi',3.75,'Postre de mango y lichi fresco de Sanghao, 150g3','11.jpg');
insert into Goods values (12,'Pescaditos de la marca Jinzai',5.79,'Pescaditos en salsa de la marca Jinzai, especialidad de Hunan, en envase de 240g','12.jpg');
insert into Goods values (13,'maní hervido',2.73,'Maní hervido con sabor a cinco especias de Mai Guo Guo, 385g','13.jpg');
insert into Goods values (14,'ciruela salada con sabor a leche fresca',2.63,'Ciruelas saladas sabor a leche fresca de Lai Yi Fen, 108g ','14.jpg');
insert into Goods values (15,'patatas fritas sabor a limón verde',2.64,'Patatas fritas sabor a limón verde de Lay''s, 70g ','15.jpg');
insert into Goods values (16,'Nabos absorbe-salsa',1.41,'Nabos absorbe-salsa de Jiang Xiaochuang, 250g (sin condimentos) ','16.jpg');
insert into Goods values (17,'Rollo relleno',1.50,'Rollo relleno sabor a chocolate de Kangshifu, 55g ','17.jpg');
insert into Goods values (18,'Pastelillos en forma de orejas de gato de Wolong',2.22,'Sabor a cinco especias, 138 gramos','18.jpg');
insert into Goods values (19,'Montón de pescados',1.61,'Esta galleta en forma de animales marinos tiene un sabor rico y está especialmente enriquecida con lecitina de huevo, brindándole una experiencia sensorial doble tanto visual como gustativa.','19.jpg');
insert into Goods values (20,'Jalea de tortuga y ginseng',4.05,' alea de tortuga y ginseng con sabor a coco y arroz morado de Sanghao, envase doble de 222g2 ','20.jpg');
insert into Goods values (21,'crujiente de olla',3.04,'Crujientes de olla sin nombre, sabor original, 210g','21.jpg');
insert into Goods values (22,'Pastelito crujiente',1.50,'Pastelito crujiente sabor original de Wangwang, 60g','22.jpg');
insert into Goods values (23,'Galletas Want Want',1.92,'Galletas Want Want Shelly Senbei 150g','23.webp');
insert into Goods values (24,'Patatas fritas',2.02,'sabor teriyaki 100g ','24.webp');
insert into Goods values (25,'pan de gambas',1.50,'Snack "pan de gambas" 40g','25.webp');
insert into Goods values (26,'Algas en tempura ',2.85,'sabor picante 40g','26.webp');
insert into Goods values (27,'Ternera seca ',4.75,'sabor satay 63g','27.webp');
insert into Goods values (28,'Galletas en palitos',2.50,'sabor fresa 55g','28.webp');
insert into Goods values (29,'Habas fritas ',1.20,'sabor 5 especias 86g','29.webp');
insert into Goods values (30,'Gelatinas',2.25,' sabor variado 360g ',' 30.webp');
insert into Goods values (31,'Galleta ',2.95,'Galleta con sabor a chocolate Shin Chan 25g ','31.webp');
insert into Goods values (32,'Caramelo',1.75,'Caramelo explosivo multifrutas 30g 20u','32.webp');
insert into Goods values (33,'Mochi',3.50,'sabor arándanos 210g ','33.webp');
insert into Goods values (34,'Aros de cebolla fritas',1.50,'Aros de cebolla fritas 40g Oishi','34.webp');
